dist: trusty
language: java
jdk: openjdk8
services:
  - docker
python:
  - "3.6"
cache: pip

# define docker image organisation and name, which should be the same as those in the snakefile
# make sure $DOCKERHUB_USERNAME and $DOCKERHUB_PASSWORD as encrypted environment variables
env:
  global:
    - DOCKERHUB_ORGANISATION=komparo
    - DOCKERHUB_REPO=tde_dataset_dyntoy

# install -------------------------------------------------------------------------------------
# - pull cache from dockerhub (based on https://medium.com/mobileforgood/coding-tips-patterns-for-continuous-integration-with-docker-on-travis-ci-9cedb8348a62)
# - build container
# - push container
# - install nextflow
before_install:
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  - docker pull ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO} || true
install:
  #- docker build --pull --cache-from ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO} --tag ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO} .
  #- docker push ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}
  - mkdir /tmp/nextflow
  - cd /tmp/nextflow
  - wget -qO- get.nextflow.io | bash
  - export PATH=/tmp/nextflow:$PATH
after_install:
  - docker images

# script -------------------------------------------------------------------------------------
# - run test with nextflow
script:
  - nextflow run workflow.nf -resume --test=true

# deploy -------------------------------------------------------------------------------------
# - todo: send message to webhook for pull request in main repo
deploy:
  provider: script
  script: echo "deploy!"
  on:
    branch: master
  skip_cleanup: true