dist: trusty
language: python
python:
  - "3.7"
services:
  - docker

# define docker image organisation and name, which should be the same as those in the snakefile
# make sure $DOCKERHUB_USER and $DOCKER_PASSWORD as encrypted environment variables
env:
  global:
    - DOCKERHUB_ORGANISATION=komparo
    - DOCKERHUB_REPO=tde_datasets_dyntoy

# install -------------------------------------------------------------------------------------
# - pull cache from dockerhub (based on https://medium.com/mobileforgood/coding-tips-patterns-for-continuous-integration-with-docker-on-travis-ci-9cedb8348a62)
# - build container
# - install conda and snakemake
# - push container
before_install:
  - docker pull ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO} || true
  - git clone https://github.com/komparo/travis_scripts.git
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
install:
  - docker build --pull --cache-from ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO} --tag ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO} .
  - docker push ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}
  - source travis_scripts/install_snakemake.sh
  - source travis_scripts/install_singularity.sh
after_install:
  - docker images

# script -------------------------------------------------------------------------------------
# - run snakemake test rule
script:
  - snakemake test --use-singularity

# deploy -------------------------------------------------------------------------------------
# - todo: send message to webhook for pull request in main repo
deploy:
  provider: script
  script: echo "deploy!"
  on:
    branch: master
